### ISSUE TITLE
Setup instruction of adding a secret to your deployment

### ISSUE THREAD

**Issue by davidcheung** [commit-app-playground/backend-template#6]
potentially what we can do is have
- a secret template in the folder, lets say `./secrets/secrets.yml`
- a gitignore  ignoring that secret folder  `secrets/*.yml`
- then a bash script that would apply the secret manifest `scripts/apply-secrets.sh` (will only work when connected to k8s)
- a block to either uncomment or copy/paste into deployment.yml mounting the secret
-  a readme that gives some instruction on how to add that secret into k8s

**Comment by davidcheung** [comment]
The [current implementation is also missing `https://` in the ingress annotation](https://github.com/commit-app-playground/backend-template/blob/main/templates/kubernetes/deploy/ingress.yml#L14), but changing this implementation will make fixing this obsolete.

**Comment by lncramer** [comment]
Addressed by https://github.com/commit-app-playground/backend-template/pull/8
